#!/usr/bin/env bash

# Install nginx if not already installed
apt-get update -y
apt-get install nginx -y

cat > /etc/nginx/sites-available/temp_conf <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

ln -sf /etc/nginx/sites-available/temp_conf /etc/nginx/sites-enabled/temp_conf

rm -f /etc/nginx/sites-enabled/default

service nginx restart
