#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP response header

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i '/server_name _;/a \\n\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

sudo systemctl restart nginx
