#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.*

echo "ENABLED=1" > /etc/default/haproxy

cat <<EOF >> /etc/haproxy/haproxy.cfg
listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 530664-web-01 100.24.205.99:80 check
    server 530664-web-02 3.89.146.109:80 check
EOF

service haproxy start
